# Le agregamos "?createDatabaseIfNotExist=true" para que cree la base de datos si no existe
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cosarbo_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#en password deben poner la siguiente linea para que funcione localmente spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tu contraseña local de workbrench o el que uses}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Se cambió "validate" por "update" para que vuelva a crear las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=none

# Configuración de Cloudinary
cloudinary.cloud-name=deqv8wwjo
cloudinary.api-key=652324187539779
cloudinary.api-secret=sDTWS5OrRmrtwHb6hTgJlSdA964
