# Le agregamos "?createDatabaseIfNotExist=true" para que cree la base de datos si no existe
spring.datasource.url=jdbc:mysql://localhost:3306/cosarbo_db?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cambiamos "validate" por "update" para que vuelva a crear las tablas automáticamente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always